### PR TITLE
🌳 Feature - Switch to vis-timeline from vis

### PR DESCRIPTION
**Pull request by jwarykowski**
# Overview
This PR switches the vis package to vis-timeline

## Dependencies
N/A

## Outstanding Tasks
- [x] version
- [x] update examples folder with latest version

### CODE REVIEW

**Review by willmcclellan — APPROVED** [review]

**Comment by msimonian77** [comment]
Thanks for this change! Can you guys merge it?

**Comment by msimonian77** [comment]
Can someone please merge the changes? Thanks!

**Comment by razbensimon** [comment]
https://www.npmjs.com/package/react-vis-timeline

**Comment by msimonian77** [comment]
Thank you!!! :)

**Pull request closed without merging**
