### PR TITLE
19 - set selection fix

### PR DESCRIPTION
**Pull request by jonathanchrisp**
# Overview
This PR fixes an issue where shouldComponentUpdate doesn't take into consideration any selection change, therefore it doesn't re-render. I've also included some nice little updates.

## Updates
* Updated shouldComponentUpdate
* Renamed LICENSE and README to consistent naming conventions
* Updated .npmignore to ignore extra files/folders
* Added .github templates so we can get some useful information on PR's 💃 

## Dependencies
N/A

## Outstanding Tasks
- [x] Functional testing using a beta version
- [x] Update example 🤔

### CODE REVIEW

**Comment by willmcclellan** [comment]
Nice work @jonathanchrisp. Would be good to update the example so we can verify it and use it as test for future

**Comment by chocholand** [comment]
@jonathanchrisp  @willmcclellan  I added example #24

**Comment by jonathanchrisp** [comment]
Sorry @chocholand, we've been pretty busy, I'll try and get round to this in the next day or so.

**Comment by jonathanchrisp** [comment]
@willmcclellan merged the example that @chocholand added in the other PR.

**Comment by jonathanchrisp** [comment]
Hey @chocholand, I've published a new beta version for this package `1.3.4-beta`. If possible are you able to test to ensure this version works as expected? We'll test our side also but just want to double check this resolves your original issue before merging.

**Comment by chocholand** [comment]
@jonathanchrisp 
I reproduced in chrome. #19 
you can check if you put "debugger;" at 122 line in Timeline.js.

**Pull request merged**
