### PR TITLE
Update for React 16 & performance improve

### LINKED ISSUE #22: Toggle nested groups
I don't think toggling nested groups works. I forked the repository to see if I can figure it out but I'm running into trouble running this locally.

Changing import Timeline from 'react-vjsjs-timeline' in examples/src/App.js to import Timeline from '../../build' causes a bunch of dependency issues. Are there any instructions on how to test my changes?

Failed to compile.

Error in ../build/index.js
Module not found: 'style' in ~/react-visjs-timeline/build

 @ ../build/index.js 13:0-27

### PR DESCRIPTION
**Pull request by inDream**
Fix #22 #28 
Merge changes from #20 #23
Added handle `selection`, `currentTime` changes
Improve performance by changing `setGroups` before `setItems`.

*For `currentTime` I change the window instead of `currentTime` to preserve the auto update behavior when init without `currentTime` and want to navigate to another date by changing `currentTime`.

### CODE REVIEW

**Comment by mouhsinelonly** [comment]
will this be merged soon

**Comment by harmon25** [comment]
any progress on merging these changes?
[Fiber is ready!](http://isfiberreadyyet.com/)

**Comment by mouhsinelonly** [comment]
Can you please merge this

**Comment by jseminck** [comment]
I'd also like to see this merged. 👍

**Comment by willmcclellan** [comment]
Apologies for the delay, we'll take a look at this on Monday and look to get it merged 👍

**Comment by jseminck** [comment]
Thanks. 😄 I'm hoping this change will decrease the bundle size because the whole vis is no longer imported, but just the graph2d part 🎉

**Comment by willmcclellan** [comment]
Merged and published on npm v1.4.0.

Thanks for this @inDream! Build size should reduce dramatically which is awesome because visjs is just a huge dependency 👏 👏 👏

**Comment by jseminck** [comment]
Seems to be working fine 🎉 Here's a before and after of the dependency in our bundle:

screen shot 2017-09-04 at 10 46 49

screen shot 2017-09-04 at 10 43 54

**Pull request merged**
