### PR TITLE
Add currentTime prop

### PR DESCRIPTION
**Pull request by ldabiralai**
This allows you to override the time set by visjs.

Works in the same way as specified here: http://visjs.org/docs/timeline/#Methods

### CODE REVIEW

**Comment by ldabiralai** [comment]
I've also added support for groups, taken from #3

**Comment by willmcclellan** [comment]
Awesome, thanks for this @ldabiralai. Does this handle groups optionally, i.e. if you just pass items?

**Comment by ldabiralai** [comment]
Thanks for taking a look @willmcclellan 😀 

There's actually an issue at the moment with my implementation, where we default to `[]` for groups, but instead we should default to `null` as visjs won't display any items if they don't map to a group when group is `[]`, here https://github.com/almende/vis/blob/master/lib/timeline/Timeline.js#L38

I'll go ahead and update this, so the `defaultProp` is null (just to be verbose about it).

Feel free to push back if you don't think this is the way to do it.

**Comment by willmcclellan** [comment]
Looks great, thanks @ldabiralai! 👍

**Pull request merged**
